apiVersion: civo.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: civo-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: civo-creds
      namespace: crossplane-system
      key: credentials
