apiVersion: civo.upbound.io/v1alpha1
kind: CivoFirewall
metadata:
  name: k8s-firewall
spec:
  forProvider:
    networkIdRef:
      name: tf-net
    name: "k8s-firewall"
    createDefaultRules: true
    ingressRule:
    - protocol: "tcp"
      portRange: "6443"
      cidr: ["0.0.0.0/0"]
      label: "kubernetes-api-server"
      action: "allow"
    - protocol: "tcp"
      portRange: "443"
      cidr: ["0.0.0.0/0"]
      label: "https"
      action: "allow"
    - protocol: "tcp"
      portRange: "80"
      cidr: ["0.0.0.0/0"]
      label: "http"
      action: "allow"
    egressRule:
    - label: "all"
      protocol: "tcp"
      portRange: "1-65535"
      cidr: ["0.0.0.0/0"]
      action: "allow"
  providerConfigRef:
    name: civo-provider